### ISSUE TITLE
Chrome autodeletes

### ISSUE THREAD

**Issue by RamonSteiner** [JackCDK/osprey#3]
Not sure if I did something wrong. I installed osprey, installed some old themes and everything works great! Restart chrome and chrome notifies me it disabled extensions not from their store. I cant re-enable it either. Is there a workaround?

**Comment by JackCDK** [comment]
Yes there is. Chrome is removing my extension because it is not coming from the chrome store. I've payed the $5 fee and I am sorting out the page for it right now!

**Comment by JackCDK** [comment]
Right the status is "Publishing in progress" I'll post the link once it's done.

**Comment by JackCDK** [comment]
Ok here is the store page link for osprey
https://chrome.google.com/webstore/detail/osprey/ekjapccimkannnfgcnnoajhfdglobgak
