### ISSUE TITLE
Style Deletion Confirmation is cut off by monitor edge

### ISSUE THREAD

**Issue by RalphORama** [JackCDK/osprey#4]
When selecting "delete style" while Chrome is full screen or maximized (or on the right side of the screen), the confirmation dialog is cut off.

![Figure 1](https://cloud.githubusercontent.com/assets/6566104/22052472/7670effa-dd18-11e6-815b-c527baaf601f.png)

**Comment by JackCDK** [comment]
Ok for now you'll have to just drag it into your screen to confirm it. I'll be working on a fix

**Comment by JackCDK** [comment]
This helps by removing the confirmation box all together.

**Comment by JackCDK** [comment]
I'll push the update on the chrome store
