### ISSUE TITLE
New Tabs

### ISSUE THREAD

**Issue by Dbakk** [JackCDK/osprey#9]
When I open another tab of the "ospreyed" webpage, the style doesnt apply to the new page. Is there a setting or fix for this?

The only way I have found it to work is to deactivate and reactivate.

**Comment by JackCDK** [comment]
I have tried what you say on 4 different computers with osprey and haven't been able to replicate what you describe. Are you sure you don't have any other extensions interfering with osprey? other than that I don't know what could be wrong for you.

**Comment by Dbakk** [comment]
Ok, so I did a little more testing to get a more specific example for you of what is going on. What is happening is when I open a new tab from the current tab that has the style in use, the new tab is not applying the new style. What is weird about it, is some of the style is applied, but majority of it is not working. Let me know if you need more clarification on that. I'm not sure I'm making complete sense trying to describe what is happening.

**Comment by JackCDK** [comment]
I understand fully what you are describing but I'm just not able to replicate what you say.

**Comment by JackCDK** [comment]
Since no further information has came up, I'll close this issue.
